import DrugTable, { DrugEntry } from '../DrugTable';

export default function DrugTableExample() {
  // todo: remove mock functionality
  const mockData: DrugEntry[] = [
    {
      id: "1",
      drugName: "Pembrolizumab",
      target: "PD-1",
      stage: "Approved",
      moleculeType: "Monoclonal Antibody",
      company: "Merck",
      indication: "Melanoma, NSCLC",
      isNew: true,
    },
    {
      id: "2",
      drugName: "Osimertinib",
      target: "EGFR",
      stage: "Approved",
      moleculeType: "Small Molecule",
      company: "AstraZeneca",
      indication: "NSCLC",
      isNew: true,
    },
    {
      id: "3",
      drugName: "Trastuzumab",
      target: "HER2",
      stage: "Approved",
      moleculeType: "Monoclonal Antibody",
      company: "Roche",
      indication: "Breast Cancer",
      isNew: false,
    },
    {
      id: "4",
      drugName: "Imatinib",
      target: "BCR-ABL",
      stage: "Approved",
      moleculeType: "Small Molecule",
      company: "Novartis",
      indication: "CML",
      isNew: false,
    },
    {
      id: "5",
      drugName: "Bevacizumab",
      target: "VEGF",
      stage: "Approved",
      moleculeType: "Monoclonal Antibody",
      company: "Roche",
      indication: "Colorectal Cancer",
      isNew: false,
    },
    {
      id: "6",
      drugName: "Rituximab",
      target: "CD20",
      stage: "Approved",
      moleculeType: "Monoclonal Antibody",
      company: "Roche",
      indication: "NHL, CLL",
      isNew: false,
    },
    {
      id: "7",
      drugName: "ABX-101",
      target: "EGFR",
      stage: "Phase III",
      moleculeType: "Small Molecule",
      company: "Ablynx Pharma",
      indication: "NSCLC",
      isNew: false,
    },
    {
      id: "8",
      drugName: "Nivolumab",
      target: "PD-1",
      stage: "Approved",
      moleculeType: "Monoclonal Antibody",
      company: "Bristol Myers Squibb",
      indication: "Melanoma, RCC",
      isNew: false,
    },
    {
      id: "9",
      drugName: "GEN-202",
      target: "HER2",
      stage: "Phase II",
      moleculeType: "Biologic",
      company: "Genentech",
      indication: "Gastric Cancer",
      isNew: false,
    },
    {
      id: "10",
      drugName: "VX-450",
      target: "VEGF",
      stage: "Phase I",
      moleculeType: "Small Molecule",
      company: "Vertex",
      indication: "Solid Tumors",
      isNew: false,
    },
  ];

  return <DrugTable data={mockData} />;
}
